### ISSUE TITLE
Release usable with new at least cake 26.0

### ISSUE THREAD

**Issue by sqeezy** [agc93/Cake.Vagrant#10]
Hi there,

I started using Cake.Vagrant a few years back for some internal deployments. The current release is not compatible with the current cake versions is therefore not usable. Are you interested in someone else solving that problem or is this project just dead?

I would be glad to help.

Regards

**Comment by gep13** [comment]
@sqeezy no, this project isn't dead, just not a priority currently 😢 

I am going to say that the problem that you are facing is this one:

![image](https://user-images.githubusercontent.com/1271146/52180689-57763400-27e1-11e9-89aa-0ca04b990f11.png)

Which, as mentioned in the output can be worked around by setting the `skipverification` flag.  This can be done either via an environment variable, as part of the cake.config file, or by passing in as an argument to the invocation of Cake.  See the documentation here:

https://cakebuild.net/docs/fundamentals/configuration

For more information.
