### ISSUE TITLE
Set up GitHub pages for this repo

### ISSUE THREAD

**Issue by gep13** [agc93/Cake.Vagrant#3]
- As I don't think that the existing GH-Pages is coming to work anymore.

@agc93 what are your thoughts?

**Comment by agc93** [comment]
If you do the initial setup, shouldn't I be able to just push to the `gh-pages` on this repo, same as on the old one? Then, I can work out how to add it to the build process (as we discussed on Gitter last week). 

I may however be missing something really obvious here? :laughing:

**Comment by gep13** [comment]
@agc93 assume here that I have never done anything with GH-Pages :-)  I know what they are, and in concept how they work, but no idea how to set them up, or whether there are differences in how they work at the organisation level compared to the individual user setup.

**Comment by gep13** [comment]
@agc93 okay, so if I have read this properly, it should "just" work:

https://help.github.com/articles/user-organization-and-project-pages/#project-pages

**Comment by agc93** [comment]
I think there may be an option to turn it on on the Settings page: there was for user repos when I set it up.  I'm assuming I have all the needed permissions at this point (i.e. write/push access etc)?

**Comment by gep13** [comment]
Which it does:

https://cake-contrib.github.io/Cake.Vagrant/

😄

**Comment by agc93** [comment]
Awesome :grinning:

**Comment by gep13** [comment]
> @agc93 said...
> I'm assuming I have all the needed permissions at this point (i.e. write/push access etc)?

Assuming you have accepted the Organization invite, then yes, you should have the same access that you had before.  If you don't then let me know.

**Comment by gep13** [comment]
![image](https://cloud.githubusercontent.com/assets/1271146/18416261/592cc96c-7807-11e6-8d04-7496bd7dc50f.png)

@agc93 ^^

**Comment by agc93** [comment]
@gep13 accepted now. Was checking GitHub notifications, forgot to check my email :smile:

**Comment by gep13** [comment]
Nice one!
