### ISSUE TITLE
Update nuspec with Cake Contrib Icon

### ISSUE THREAD

**Issue by gep13** [agc93/Cake.Vagrant#4]

**Comment by agc93** [comment]
What do you think of this as a middle ground @gep13 ?

![screenshot 75](https://cloud.githubusercontent.com/assets/1369269/20238115/6ac75062-a92f-11e6-9af4-4bb4495a89f2.png)

(obviously replace transparency with white)

**Comment by gep13** [comment]
@agc93 have you obtained permission from Hashicorp to use the Vagrant icon? How is it licensed?

**Comment by agc93** [comment]
Vagrant itself is MIT, and their website indicates no copyright for the logo or even the name, and the logo is listed on Wikipedia as CC-BY-SA. Is it worth maybe adding a disclaimer to the README just in case?

**Comment by gep13** [comment]
Yes, I think that would be best.

Do you think it might be worth inverting the image, so that it is more like: https://www.nuget.org/packages/Cake.Xamarin/

i.e. where Cake is the main portion of the icon?

**Comment by agc93** [comment]
Yeah I might switch that around and give it a look, then I'll add a basic "all rights reserved" disclaimer about the logo on the README.

**Comment by gep13** [comment]
Sounds good to me. :+1:

**Comment by agc93** [comment]
![screenshot 78](https://cloud.githubusercontent.com/assets/1369269/20355631/b0965e62-ac6d-11e6-8c29-991c29fa9f44.png)

Doesn't work quite as well but is probably a bit clearer

**Comment by gep13** [comment]
@agc93  LGTM! 👍

**Comment by gep13** [comment]
Thanks again for creating this Cake Addin, we really appreciate the effort that you have put in to creating it.  

We, the Cake Team, recently announced a new Cake Contrib Icon, details of which can be found here:

http://cakebuild.net/blog/2017/06/new-cake-contrib-icon

Would you consider changing the nuspec file for your NuGet Package to use this new Cake Contrib Icon?  If so, the recommended URL to use is:

https://cdn.rawgit.com/cake-contrib/graphics/a5cf0f881c390650144b2243ae551d5b9f836196/png/cake-contrib-medium.png

Details of the above URL can be found in the repository here:

https://github.com/cake-contrib/graphics

Please let me know if you have any questions.

**Comment by agc93** [comment]
@gep13 Icon updated as discussed: 

https://www.nuget.org/packages/Cake.Vagrant/0.4.0-unstable0006

Will go stable with next release :smile:

**Comment by gep13** [comment]
:+1:
